### ISSUE TITLE
Rewrite in rust

### ISSUE THREAD

**Issue by ishioni** [AlynxZhou/gnome-shell-extension-inotch#18]
This extension while nice is written in a non-safe language, and should be rewritten in rust

**Comment by alula** [comment]
javascript is safe...

**Comment by AlynxZhou** [comment]
> javascript is safe...

Rust programmers are passionate to rewrite the whole world with rust XD, and some of them really made great alternatives, I personlly like ripgrep/bat/exa/fd.

**Comment by Skaldebane** [comment]
Late to the party, but I believe GNOME Extensions cannot be written in any language other than JS?

Anyways, the issue with JavaScript isn't safety (it's safe by default), but with the performance and stability issues it has. Not having a rigid type system, plus being an interpreted and garbage-collected language, which definitely leaks into the GNOME Shell and causes some rather surprising bugs to happen.
JS was chosen because being an interpreted language means that it's easy to inject into an already running system, without having to build anything. That's great and easy for an extensible system like the GNOME Shell, though it comes with drawbacks as mentioned before.

Unfortunately JS is the only way now, but I hope that we can some day to do it in Rust, maybe by distributing optimized library files that conform to some specification the Shell enforces, or maybe building it as an extension to the shell on install (like kernel modules do?), that the shell can then run.

**Comment by kodmanyagha** [comment]
I think gnome must allow different languages for developing extension. Javascript is cumbersome language and I don't feel myself comfortable when using extensions. Yes they work, yes they fine, but there are lots of oldschool linux users (like me) and we feel performance bottlenecks even they are in only milliseconds.

Also rust developers wants rewrite everything with rust this is correct. I'm one of them 😄

**Comment by skaldebane** [comment]
Interesting to see this revived a couple years later xD

I still hold the opinion that JS isn't the best fit for the shell, but the benefit it brings is this modularity. In my last response, I wasn't sure _how_ could we even use other languages, but I guess there's only one way to do that properly, and that's **WebAssembly**.

That would allow basically most programming languages out there, including Rust, Kotlin, C, or really anything that can compile down to Wasm bytecode. The only challenge is in _how_ to expose the APIs to these languages. The biggest use-case for WebAssembly nowadays in the browser still relies on going through JS to access browser APIs (that's WasmJS). It would make for a quick and easy way to add this to shell without a lot more work.
What would be even better though is Wasi (WebAssembly System Interface) support, alongside Wasm modules. This way shell can export its own Wasm module, that other languages can use. However Wasm Modules support is still very limited in most languages.

I rambled a lot, probably not the right place to discuss this, but this goes beyond Rust. As for JS, it's probably a very fine language for the use-cases extensions provide, since most of the work is delegated to lower layers anyways. It's still not very great, but it does job.
